name: Run unit tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: create environment with conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: false
          activate-environment: ABR
          environment-file: env.yaml  

      - name: install dependencies with pip
        run: |
          conda activate ABR
          pip install -r requirements.txt     

      - name: Run Tests
        run: pytest tests